aur:
  - dropbox-cli
  - i3blocks
  - jre-devel
  - neofetch
  - playerctl
  - polysh
  - spotify
  - telegram-desktop-bin
  - tcptraceroute
  - terminus-font-ttf
  - ttf-font-awesome
  - ttf-share-gf
